### ISSUE TITLE
Improve the non-breakingness of lineToHtml

### ISSUE THREAD

**Issue by gbaz** [haskell/xhtml#11]
The lineToHtmlFunction: https://github.com/haskell/xhtml/blob/master/Text/XHtml/Extras.hs#L17

is written as:

```
-- | This converts a string, but keeps spaces as non-line-breakable.
lineToHtml :: String -> Html
lineToHtml = primHtml . concatMap htmlizeChar2 . stringToHtmlString 
   where 
      htmlizeChar2 ' ' = "&nbsp;"
      htmlizeChar2 c   = [c]
```

I would suggest it keep spaces _and_ hyphens as non-line-breakable. This just means adding an extra case `htmlizeChar2 '-' = "&#8209;"`.

**Comment by hvr** [comment]
Hrm... why just ascii dashes and not all the other Unicode punctuation symbols which have a similar function to ASCII dashes? :-)

**Comment by gbaz** [comment]
I think the full set varies by region! That said, there's a core set that includes a few other characters and not much else here: http://unicode.org/reports/tr14/ (look at: "Break Opportunities"). On the other hand, we don't need to get too fancy, as honestly this is sort of legacy-ish code, and the "right" way these days is to use the wrapping properties of css in spans, probably.

**Comment by gbaz** [comment]
actually, going to close this, as the modern way is to use `white-space: nowrap` spans, and the entire special character thing is sorta hacky and probably shouldn't be encouraged further anyway :-)
