### ISSUE TITLE
Hackage release for 3000.4.0.0

### ISSUE THREAD

**Issue by wz1000** [haskell/xhtml#21]
We need a hackage release for version [3000.4.0.0](https://github.com/haskell/xhtml/commit/322108f03f8031bffb9b460aa513306a72a7a6e8) for GHC 9.12

**Comment by Kleidukos** [comment]
Done, https://hackage.haskell.org/package/xhtml-3000.4.0.0 is published alongside the tag https://github.com/haskell/xhtml/releases/tag/3000.4.0.0
